from __future__ import annotations

from enum import StrEnum


class ChatAction(StrEnum):
    USER_MESSAGE = "user_message"
    SESSION_CREATED = "session_created"
    BIND_OK = "bind_ok"
    UNBIND_OK = "unbind_ok"
    STREAM = "stream"
    LLM_FIRST_TOKEN = "llm_first_token"
    SYSTEM_MESSAGE = "system_message"
    COMPLETED = "completed"
    CANCELLED = "cancelled"
    TOOL_START = "tool_start"
    TOOL_PROGRESS = "tool_progress"
    TOOL_END = "tool_end"
    A2UI_STREAM_START = "a2ui_stream_start"
    A2UI_STREAM_CHUNK = "a2ui_stream_chunk"
    A2UI_STREAM_FINISH = "a2ui_stream_finish"
    A2UI_CREATED = "a2ui_created"
    WAITING_INPUT = "waiting_input"
    A2UI_SUBMIT_ACK = "a2ui_submit_ack"
    A2UI_CANCEL_ACK = "a2ui_cancel_ack"
    A2UI_RESUME = "a2ui_resume"
    APPROVAL_REQUESTED = "approval_requested"
    APPROVAL_RESOLVED = "approval_resolved"
    SUBAGENT_START = "subagent_start"
    SUBAGENT_END = "subagent_end"
    SUBAGENT_ERROR = "subagent_error"
    ERROR = "error"
    PONG = "pong"
    STATUS = "status"
    SESSION_CLOSED = "session_closed"
    SESSION_TITLE_UPDATED = "session_title_updated"
    TASK_RESULT = "task_result"
    TASK_UPDATED = "task_updated"
    TASK_DELETED = "task_deleted"
    TASK_RUN_STARTED = "task_run_started"
    TASK_RUN_FINISHED = "task_run_finished"
    TURN_STARTED = "turn_started"
    THREAD_TASK_STATUS = "thread_task_status"
    REASONING = "reasoning"
    MIDDLEWARE_PROGRESS = "middleware_progress"
    PENDING_INPUT_SUBMITTED = "pending_input_submitted"
    PENDING_INPUT_UPDATED = "pending_input_updated"
    PENDING_INPUTS_REORDERED = "pending_inputs_reordered"
    PENDING_INPUT_CANCELLED = "pending_input_cancelled"
    PENDING_INPUT_DELIVERED = "pending_input_delivered"
    PENDING_INPUT_CONVERTED = "pending_input_converted"
    PENDING_INPUT_PAUSED = "pending_input_paused"
    PENDING_INPUT_RESUMED = "pending_input_resumed"
    PENDING_INPUT_FAILED = "pending_input_failed"


class ReplayAction(StrEnum):
    USER_MESSAGE = "user_message"
    SYSTEM_MESSAGE = "system_message"
    AI_MESSAGE = "ai_message"
    STREAM_BATCH = "stream_batch"
    TOOL_START = "tool_start"
    TOOL_END = "tool_end"
    A2UI_CREATED = "a2ui_created"
    WAITING_INPUT = "waiting_input"
    APPROVAL_REQUESTED = "approval_requested"
    APPROVAL_RESOLVED = "approval_resolved"
    SUBAGENT_START = "subagent_start"
    SUBAGENT_END = "subagent_end"
    SUBAGENT_ERROR = "subagent_error"
    MEMORY_RECALLED = "memory_recalled"
    COMPLETED = "completed"
    CANCELLED = "cancelled"
    ERROR = "error"
    SCHEDULED_TASK_RESULT = "scheduled_task_result"
    TASK_UPDATED = "task_updated"
    TASK_DELETED = "task_deleted"
    TASK_RUN_STARTED = "task_run_started"
    TASK_RUN_FINISHED = "task_run_finished"
    TURN_STARTED = "turn_started"
    THREAD_TASK_STATUS = "thread_task_status"
    REASONING = "reasoning"
    MIDDLEWARE_PROGRESS = "middleware_progress"
    PENDING_INPUT_SUBMITTED = "pending_input_submitted"
    PENDING_INPUT_UPDATED = "pending_input_updated"
    PENDING_INPUTS_REORDERED = "pending_inputs_reordered"
    PENDING_INPUT_CANCELLED = "pending_input_cancelled"
    PENDING_INPUT_DELIVERED = "pending_input_delivered"
    PENDING_INPUT_CONVERTED = "pending_input_converted"
    PENDING_INPUT_PAUSED = "pending_input_paused"
    PENDING_INPUT_RESUMED = "pending_input_resumed"
    PENDING_INPUT_FAILED = "pending_input_failed"


class CompletedEventItemAction(StrEnum):
    AI_MESSAGE = "ai_message"
    TOOL_START = "tool_start"
    TOOL_END = "tool_end"
    STREAM = "stream"
    REASONING_MESSAGE = "reasoning_message"


class ChatInboundAction(StrEnum):
    CREATE_SESSION = "create_session"
    BIND_SESSION = "bind_session"
    UNBIND_SESSION = "unbind_session"
    CHAT = "chat"
    SCHEDULED_CHAT = "scheduled_chat"
    CLOSE_SESSION = "close_session"
    CANCEL = "cancel"
    A2UI_SUBMIT = "a2ui_submit"
    A2UI_CANCEL = "a2ui_cancel"
    APPROVAL_DECISION = "approval_decision"
    PENDING_INPUT_UPDATE = "pending_input_update"
    PENDING_INPUT_REORDER = "pending_input_reorder"
    PENDING_INPUT_CANCEL = "pending_input_cancel"
    PENDING_INPUT_RESUME = "pending_input_resume"
    PING = "ping"
    GET_STATUS = "get_status"
