export const KEYDEX_DIFF_DESIGN_TOKENS = Object.freeze([
  "--diff-surface-bg",
  "--diff-surface-muted",
  "--diff-surface-elevated",
  "--diff-code-text",
  "--diff-border-subtle",
  "--diff-border-default",
  "--diff-header-bg",
  "--diff-gutter-bg",
  "--diff-gutter-text",
  "--diff-gutter-text-active",
  "--diff-line-number",
  "--diff-line-number-active",
  "--diff-added-bg",
  "--diff-added-text",
  "--diff-added-border",
  "--diff-added-word-bg",
  "--diff-removed-bg",
  "--diff-removed-text",
  "--diff-removed-border",
  "--diff-removed-word-bg",
  "--diff-context-hover-bg",
  "--diff-hunk-bg",
  "--diff-hunk-text",
  "--diff-hunk-border",
  "--diff-selection-bg",
  "--diff-selection-border",
  "--diff-annotation-bg",
  "--diff-annotation-text",
  "--diff-annotation-border",
  "--diff-focus-ring",
  "--diff-scrollbar-track",
  "--diff-scrollbar-thumb",
  "--diff-scrollbar-thumb-hover",
  "--diff-toolbar-bg",
  "--diff-toolbar-border",
  "--diff-toolbar-control-hover",
  "--diff-toolbar-control-active",
] as const);

export const KEYDEX_LEGACY_DIFF_TOKENS = Object.freeze([
  "--diff-added-glow",
  "--diff-removed-glow",
] as const);
